name: Deploy React Book App from GitHub to EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v2

      - name: Generate Deployment Package
        run: |
          npm install
          npm run build
          zip -r build.zip build/

      - name: Copy Deployment Package to EC2
        uses: appleboy/scp-action@v2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          source: build.zip
          target: /path/to/remote/directory

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            cd /path/to/remote/directory
            unzip -o build.zip -d /var/www/html
